# This is a basic workflow to help you get started with Actions

name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: congaterori
          plugin_anilist_user: johnny20061234
          filename: metrics.svg
          token: ${{ secrets.TOKEN }}
          #template: classic
          #base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          plugin_anilist: yes
          plugin_anilist_limit.characters: 22
          plugin_anilist_limit: 5
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_shuffle: yes
          plugin_people: yes
          plugin_people_types: followers, thanks
          plugin_people_limit: 50
          plugin_people_size: 50
          plugin_people_identicons: no
          plugin_people_thanks: lowlighter, octocat
          plugin_people_sponsors_custom: octocat
          plugin_people_shuffle: yes
